# Site settings
title: Expertise Process Associate Consultants
email: info@ep-ac.be
description: > # this means to ignore newlines until "baseurl:"
  An consultant company, built by experts, for more than service
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://www.ep-ac.be" # the base hostname & protocol for your site
twitter_username: 
github_username:  nathanas13
linkedin_username:  ep-ac

# Build settings
markdown: kramdown
